# Issue 24727: KeyError in DiGraph.is_isomorphic when certificate=True

Issue created by migration from https://trac.sagemath.org/ticket/24964

Original creator: slabbe

Original creation time: 2018-03-13 13:31:41

This is okay:


```python
sage: A = DiGraph([(6,7)])
sage: B = DiGraph([('x','y')])
sage: A.is_isomorphic(B, certificate=True)
(True, {6: 'x', 7: 'y'})
```


This is okay with multiedges without asking for the certificate:


```python
sage: A = DiGraph([(6,7,'a'), (6,7,'b')],multiedges=True)
sage: B = DiGraph([('x','y', 'u'), ('x','y','v')], multiedges=True)
sage: A.is_isomorphic(B)
True
```


But when asking for the certificate, one gets a KeyError


```python
sage: A = DiGraph([(6,7,'a'), (6,7,'b')],multiedges=True)
sage: B = DiGraph([('x','y', 'u'), ('x','y','v')], multiedges=True)
sage: A.is_isomorphic(B, certificate=True)
Traceback (most recent call last):

.../sage/local/lib/python2.7/site-packages/sage/graphs/generic_graph.pyc in is_isomorphic(self, other, certificate, verbosity, edge_labels)
  22033             else:
  22034                 for v in self.vertices():
> 22035                     isom_trans[v] = other_vertices[isom[G_to[v]]]
  22036             return True, isom_trans
  22037

KeyError: 6
```


Also, without labels:


```python
sage: A = DiGraph([(6,7), (6,7)],multiedges=True)
sage: B = DiGraph([('x','y'), ('x','y')], multiedges=True)
sage: A.is_isomorphic(B, certificate=True)
Traceback (most recent call last):
...
KeyError: 6
```



---

Comment by slabbe created at 2018-03-13 13:59:38

New commits:


---

Comment by slabbe created at 2018-03-13 13:59:38

Changing status from new to needs_review.


---

Comment by dcoudert created at 2018-03-13 16:55:42

Changing status from needs_review to positive_review.


---

Comment by dcoudert created at 2018-03-13 16:55:42

Works fine for me. Thanks.


---

Comment by vbraun created at 2018-03-22 19:23:24

Resolution: fixed
