# Issue 28523: py3: internet str vs bytes doctests failures

archive/issues_028523.json:
```json
{
    "body": "```\nsage -t --optional=sage,optional,external src/sage/coding/databases.py\n```\n\ngives\n\n```\n----------------------------------------------------------------------\nsage -t src/sage/coding/databases.py  # 2 doctests failed\n----------------------------------------------------------------------\n```\n\nwith errors of that kind:\n\n```\nsage -t src/sage/coding/databases.py\n**********************************************************************\nFile \"src/sage/coding/databases.py\", line 137, in sage.coding.databases.best_linear_code_in_codetables_dot_de\nFailed example:\n    L = codes.databases.best_linear_code_in_codetables_dot_de(72, 36, GF(2))    # optional - internet\nException raised:\n    Traceback (most recent call last):\n      File \"/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py\", line 681, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py\", line 1123, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.coding.databases.best_linear_code_in_codetables_dot_de[0]>\", line 1, in <module>\n        L = codes.databases.best_linear_code_in_codetables_dot_de(Integer(72), Integer(36), GF(Integer(2)))    # optional - internet\n      File \"/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/coding/databases.py\", line 174, in best_linear_code_in_codetables_dot_de\n        i = s.find(\"<PRE>\")\n    TypeError: argument should be integer or bytes-like object, not 'str'\n**********************************************************************\n```\n\nIssue created by migration from https://trac.sagemath.org/ticket/28760\n\n",
    "closed_at": "2019-11-29T23:57:37Z",
    "created_at": "2019-11-19T08:47:20Z",
    "labels": [
        "component: python3",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-9.0",
    "title": "py3: internet str vs bytes doctests failures",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/28523",
    "user": "https://github.com/seblabbe"
}
```
```
sage -t --optional=sage,optional,external src/sage/coding/databases.py
```

gives

```
----------------------------------------------------------------------
sage -t src/sage/coding/databases.py  # 2 doctests failed
----------------------------------------------------------------------
```

with errors of that kind:

```
sage -t src/sage/coding/databases.py
**********************************************************************
File "src/sage/coding/databases.py", line 137, in sage.coding.databases.best_linear_code_in_codetables_dot_de
Failed example:
    L = codes.databases.best_linear_code_in_codetables_dot_de(72, 36, GF(2))    # optional - internet
Exception raised:
    Traceback (most recent call last):
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1123, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.coding.databases.best_linear_code_in_codetables_dot_de[0]>", line 1, in <module>
        L = codes.databases.best_linear_code_in_codetables_dot_de(Integer(72), Integer(36), GF(Integer(2)))    # optional - internet
      File "/home/slabbe/GitBox/sage/local/lib/python3.7/site-packages/sage/coding/databases.py", line 174, in best_linear_code_in_codetables_dot_de
        i = s.find("<PRE>")
    TypeError: argument should be integer or bytes-like object, not 'str'
**********************************************************************
```

Issue created by migration from https://trac.sagemath.org/ticket/28760





---

archive/issue_comments_402342.json:
```json
{
    "body": "src/sage/misc/persist.pyx is fixed in #28761",
    "created_at": "2019-11-19T10:50:01Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28523",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28523#issuecomment-402342",
    "user": "https://github.com/fchapoton"
}
```

src/sage/misc/persist.pyx is fixed in #28761



---

archive/issue_comments_402343.json:
```json
{
    "body": "src/sage/repl/load.py is almost fixed by #28761 too",
    "created_at": "2019-11-19T12:57:52Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28523",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28523#issuecomment-402343",
    "user": "https://github.com/fchapoton"
}
```

src/sage/repl/load.py is almost fixed by #28761 too



---

archive/issue_comments_402344.json:
```json
{
    "body": "Here is a fix for databases\n\n---\nNew commits:",
    "created_at": "2019-11-19T14:53:07Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28523",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28523#issuecomment-402344",
    "user": "https://github.com/fchapoton"
}
```

Here is a fix for databases

---
New commits:



---

archive/issue_comments_402345.json:
```json
{
    "body": "Spliting this ticket and moving the other issues to #28808",
    "created_at": "2019-11-27T15:14:41Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28523",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28523#issuecomment-402345",
    "user": "https://github.com/seblabbe"
}
```

Spliting this ticket and moving the other issues to #28808



---

archive/issue_comments_402346.json:
```json
{
    "body": "Changing status from new to needs_review.",
    "created_at": "2019-11-27T15:15:02Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28523",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28523#issuecomment-402346",
    "user": "https://github.com/seblabbe"
}
```

Changing status from new to needs_review.



---

archive/issue_comments_402347.json:
```json
{
    "body": "Changing status from needs_review to positive_review.",
    "created_at": "2019-11-27T15:15:29Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28523",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28523#issuecomment-402347",
    "user": "https://github.com/seblabbe"
}
```

Changing status from needs_review to positive_review.



---

archive/issue_comments_402348.json:
```json
{
    "body": "Resolution: fixed",
    "created_at": "2019-11-29T23:57:37Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28523",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28523#issuecomment-402348",
    "user": "https://github.com/vbraun"
}
```

Resolution: fixed



---

archive/issue_events_072579.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2019-11-29T23:57:37Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sagetest/issues/28523",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/28523#event-72579"
}
```
