# Issue 24727: KeyError in DiGraph.is_isomorphic when certificate=True

archive/issues_024727.json:
```json
{
    "body": "This is okay:\n\n\n```python\nsage: A = DiGraph([(6,7)])\nsage: B = DiGraph([('x','y')])\nsage: A.is_isomorphic(B, certificate=True)\n(True, {6: 'x', 7: 'y'})\n```\n\n\nThis is okay with multiedges without asking for the certificate:\n\n\n```python\nsage: A = DiGraph([(6,7,'a'), (6,7,'b')],multiedges=True)\nsage: B = DiGraph([('x','y', 'u'), ('x','y','v')], multiedges=True)\nsage: A.is_isomorphic(B)\nTrue\n```\n\n\nBut when asking for the certificate, one gets a KeyError\n\n\n```python\nsage: A = DiGraph([(6,7,'a'), (6,7,'b')],multiedges=True)\nsage: B = DiGraph([('x','y', 'u'), ('x','y','v')], multiedges=True)\nsage: A.is_isomorphic(B, certificate=True)\nTraceback (most recent call last):\n\n.../sage/local/lib/python2.7/site-packages/sage/graphs/generic_graph.pyc in is_isomorphic(self, other, certificate, verbosity, edge_labels)\n  22033             else:\n  22034                 for v in self.vertices():\n> 22035                     isom_trans[v] = other_vertices[isom[G_to[v]]]\n  22036             return True, isom_trans\n  22037\n\nKeyError: 6\n```\n\n\nAlso, without labels:\n\n\n```python\nsage: A = DiGraph([(6,7), (6,7)],multiedges=True)\nsage: B = DiGraph([('x','y'), ('x','y')], multiedges=True)\nsage: A.is_isomorphic(B, certificate=True)\nTraceback (most recent call last):\n...\nKeyError: 6\n```\n\n\nIssue created by migration from https://trac.sagemath.org/ticket/24964\n\n",
    "created_at": "2018-03-13T13:31:41Z",
    "labels": [
        "component: graph theory",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-8.2",
    "title": "KeyError in DiGraph.is_isomorphic when certificate=True",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/24727",
    "user": "https://github.com/seblabbe"
}
```
This is okay:


```python
sage: A = DiGraph([(6,7)])
sage: B = DiGraph([('x','y')])
sage: A.is_isomorphic(B, certificate=True)
(True, {6: 'x', 7: 'y'})
```


This is okay with multiedges without asking for the certificate:


```python
sage: A = DiGraph([(6,7,'a'), (6,7,'b')],multiedges=True)
sage: B = DiGraph([('x','y', 'u'), ('x','y','v')], multiedges=True)
sage: A.is_isomorphic(B)
True
```


But when asking for the certificate, one gets a KeyError


```python
sage: A = DiGraph([(6,7,'a'), (6,7,'b')],multiedges=True)
sage: B = DiGraph([('x','y', 'u'), ('x','y','v')], multiedges=True)
sage: A.is_isomorphic(B, certificate=True)
Traceback (most recent call last):

.../sage/local/lib/python2.7/site-packages/sage/graphs/generic_graph.pyc in is_isomorphic(self, other, certificate, verbosity, edge_labels)
  22033             else:
  22034                 for v in self.vertices():
> 22035                     isom_trans[v] = other_vertices[isom[G_to[v]]]
  22036             return True, isom_trans
  22037

KeyError: 6
```


Also, without labels:


```python
sage: A = DiGraph([(6,7), (6,7)],multiedges=True)
sage: B = DiGraph([('x','y'), ('x','y')], multiedges=True)
sage: A.is_isomorphic(B, certificate=True)
Traceback (most recent call last):
...
KeyError: 6
```


Issue created by migration from https://trac.sagemath.org/ticket/24964





---

archive/issue_comments_346703.json:
```json
{
    "body": "New commits:",
    "created_at": "2018-03-13T13:59:38Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24727",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24727#issuecomment-346703",
    "user": "https://github.com/seblabbe"
}
```

New commits:



---

archive/issue_comments_346704.json:
```json
{
    "body": "Changing status from new to needs_review.",
    "created_at": "2018-03-13T13:59:38Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24727",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24727#issuecomment-346704",
    "user": "https://github.com/seblabbe"
}
```

Changing status from new to needs_review.



---

archive/issue_comments_346705.json:
```json
{
    "body": "Changing status from needs_review to positive_review.",
    "created_at": "2018-03-13T16:55:42Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24727",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24727#issuecomment-346705",
    "user": "https://github.com/dcoudert"
}
```

Changing status from needs_review to positive_review.



---

archive/issue_comments_346706.json:
```json
{
    "body": "Works fine for me. Thanks.",
    "created_at": "2018-03-13T16:55:42Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24727",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24727#issuecomment-346706",
    "user": "https://github.com/dcoudert"
}
```

Works fine for me. Thanks.



---

archive/issue_comments_346707.json:
```json
{
    "body": "Resolution: fixed",
    "created_at": "2018-03-22T19:23:24Z",
    "issue": "https://github.com/sagemath/sagetest/issues/24727",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/24727#issuecomment-346707",
    "user": "https://github.com/vbraun"
}
```

Resolution: fixed



---

archive/issue_events_062645.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-03-22T19:23:24Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sagetest/issues/24727",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/24727#event-62645"
}
```
