# Issue 32585: fix E713 and E714 in dynamics

archive/issues_032585.json:
```json
{
    "body": "about negative comparison using \"is not\"\n\nIssue created by migration from https://trac.sagemath.org/ticket/32822\n\n",
    "created_at": "2021-11-03T20:13:49Z",
    "labels": [
        "dynamics",
        "major",
        "enhancement"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-9.5",
    "title": "fix E713 and E714 in dynamics",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/32585",
    "user": "@fchapoton"
}
```
about negative comparison using "is not"

Issue created by migration from https://trac.sagemath.org/ticket/32822





---

archive/issue_comments_464744.json:
```json
{
    "body": "New commits:",
    "created_at": "2021-11-03T20:14:13Z",
    "issue": "https://github.com/sagemath/sagetest/issues/32585",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/32585#issuecomment-464744",
    "user": "@fchapoton"
}
```

New commits:



---

archive/issue_comments_464745.json:
```json
{
    "body": "Changing status from new to needs_review.",
    "created_at": "2021-11-03T20:14:13Z",
    "issue": "https://github.com/sagemath/sagetest/issues/32585",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/32585#issuecomment-464745",
    "user": "@fchapoton"
}
```

Changing status from new to needs_review.



---

archive/issue_comments_464746.json:
```json
{
    "body": "in `src/sage/dynamics/arithmetic_dynamics/endPN_automorphism_group.py`, you could also add the missing space after `#`\n\n```diff\n-                    #range over all orders\n+                    # range over all orders\n```\n\n\nsame in `src/sage/dynamics/arithmetic_dynamics/projective_ds.py` where we see in the diff\n\n```diff\n             #computes the error bound as defined in Algorithm 3.1 of [WELLS]\n             if Res > 1:\n-                if not err is None:\n+                if err is not None:\n```\n\nand\n\n```diff\n                         #for each periodic point get the entire cycle\n-                        if not Q in periodic_points:\n+                        if Q not in periodic_points:\n```\n\n\n\nin `src/sage/dynamics/arithmetic_dynamics/wehlerK3.py`, you slightly changed the test. Is it what is expected here ?\n\n```diff\n-        if not (i in [0,1,2]) and not (j in [0,1,2]):\n+        if i not in [0, 1, 2] or j not in [0, 1, 2]:\n             raise ValueError(\"the two indexes must be either 0, 1, or 2\")\n```\n",
    "created_at": "2021-11-04T07:36:28Z",
    "issue": "https://github.com/sagemath/sagetest/issues/32585",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/32585#issuecomment-464746",
    "user": "@dcoudert"
}
```

in `src/sage/dynamics/arithmetic_dynamics/endPN_automorphism_group.py`, you could also add the missing space after `#`

```diff
-                    #range over all orders
+                    # range over all orders
```


same in `src/sage/dynamics/arithmetic_dynamics/projective_ds.py` where we see in the diff

```diff
             #computes the error bound as defined in Algorithm 3.1 of [WELLS]
             if Res > 1:
-                if not err is None:
+                if err is not None:
```

and

```diff
                         #for each periodic point get the entire cycle
-                        if not Q in periodic_points:
+                        if Q not in periodic_points:
```



in `src/sage/dynamics/arithmetic_dynamics/wehlerK3.py`, you slightly changed the test. Is it what is expected here ?

```diff
-        if not (i in [0,1,2]) and not (j in [0,1,2]):
+        if i not in [0, 1, 2] or j not in [0, 1, 2]:
             raise ValueError("the two indexes must be either 0, 1, or 2")
```




---

archive/issue_comments_464747.json:
```json
{
    "body": "Branch pushed to git repo; I updated commit sha1. New commits:",
    "created_at": "2021-11-04T10:51:01Z",
    "issue": "https://github.com/sagemath/sagetest/issues/32585",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/32585#issuecomment-464747",
    "user": "git"
}
```

Branch pushed to git repo; I updated commit sha1. New commits:



---

archive/issue_comments_464748.json:
```json
{
    "body": "Voila pour quelques espaces.\n\nConcernant le test modifi\u00e9, il est devenu plus coh\u00e9rent avec le message d'erreur, donc \u00e7a me semble correct.",
    "created_at": "2021-11-04T10:52:46Z",
    "issue": "https://github.com/sagemath/sagetest/issues/32585",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/32585#issuecomment-464748",
    "user": "@fchapoton"
}
```

Voila pour quelques espaces.

Concernant le test modifié, il est devenu plus cohérent avec le message d'erreur, donc ça me semble correct.



---

archive/issue_comments_464749.json:
```json
{
    "body": "I agree and all tests pass on my side.",
    "created_at": "2021-11-04T11:05:02Z",
    "issue": "https://github.com/sagemath/sagetest/issues/32585",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/32585#issuecomment-464749",
    "user": "@dcoudert"
}
```

I agree and all tests pass on my side.



---

archive/issue_comments_464750.json:
```json
{
    "body": "Changing status from needs_review to positive_review.",
    "created_at": "2021-11-04T11:05:02Z",
    "issue": "https://github.com/sagemath/sagetest/issues/32585",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/32585#issuecomment-464750",
    "user": "@dcoudert"
}
```

Changing status from needs_review to positive_review.



---

archive/issue_comments_464751.json:
```json
{
    "body": "Resolution: fixed",
    "created_at": "2021-11-14T17:05:29Z",
    "issue": "https://github.com/sagemath/sagetest/issues/32585",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/32585#issuecomment-464751",
    "user": "@vbraun"
}
```

Resolution: fixed
