# Issue 28131: latte interface broken with Python 3

archive/issues_027894.json:
```json
{
    "body": "\n```\n**********************************************************************\nFile \"latte.py\", line 52, in sage.interfaces.latte.count\nFailed example:\n    count(P.cdd_Hrepresentation(), cdd=True)   # optional - latte_int\nException raised:\n    Traceback (most recent call last):\n      File \"/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/sage/doctest/forker.py\", line 681, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/sage/doctest/forker.py\", line 1105, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.interfaces.latte.count[2]>\", line 1, in <module>\n        count(P.cdd_Hrepresentation(), cdd=True)   # optional - latte_int\n      File \"/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/sage/interfaces/latte.py\", line 153, in count\n        ans, err = latte_proc.communicate(arg)\n      File \"/opt/sage/sage-py3-gcc/local/lib/python3.7/subprocess.py\", line 939, in communicate\n        stdout, stderr = self._communicate(input, endtime, timeout)\n      File \"/opt/sage/sage-py3-gcc/local/lib/python3.7/subprocess.py\", line 1666, in _communicate\n        input_view = memoryview(self._input)\n    TypeError: memoryview: a bytes-like object is required, not 'str'\n**********************************************************************\n```\n\nCC:  @fchapoton @mkoeppe\n\nKeywords: py3\n\nBranch/Commit: 579e9ef6c4cc66bfcbbc0fc79d5c68153335a561\n\nReviewer: Fr\u00e9d\u00e9ric Chapoton\n\nAuthor: Vincent Delecroix\n\nResolution: fixed\n\nIssue created by migration from https://trac.sagemath.org/ticket/28131\n\n",
    "closed_at": "2019-07-11T18:54:00Z",
    "created_at": "2019-07-08T04:20:58Z",
    "labels": [
        "component: interfaces",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-8.9",
    "title": "latte interface broken with Python 3",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/28131",
    "user": "https://github.com/videlec"
}
```

```
**********************************************************************
File "latte.py", line 52, in sage.interfaces.latte.count
Failed example:
    count(P.cdd_Hrepresentation(), cdd=True)   # optional - latte_int
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/sage/doctest/forker.py", line 1105, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.interfaces.latte.count[2]>", line 1, in <module>
        count(P.cdd_Hrepresentation(), cdd=True)   # optional - latte_int
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/site-packages/sage/interfaces/latte.py", line 153, in count
        ans, err = latte_proc.communicate(arg)
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/subprocess.py", line 939, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/opt/sage/sage-py3-gcc/local/lib/python3.7/subprocess.py", line 1666, in _communicate
        input_view = memoryview(self._input)
    TypeError: memoryview: a bytes-like object is required, not 'str'
**********************************************************************
```

CC:  @fchapoton @mkoeppe

Keywords: py3

Branch/Commit: 579e9ef6c4cc66bfcbbc0fc79d5c68153335a561

Reviewer: Frédéric Chapoton

Author: Vincent Delecroix

Resolution: fixed

Issue created by migration from https://trac.sagemath.org/ticket/28131





---

archive/issue_comments_538201.json:
```json
{
    "body": "Changing status from new to needs_review.",
    "created_at": "2019-07-08T04:32:33Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538201",
    "user": "https://github.com/videlec"
}
```

Changing status from new to needs_review.



---

archive/issue_comments_538202.json:
```json
{
    "body": "Changing branch from \"\" to \"u/vdelecroix/28131\"",
    "created_at": "2019-07-08T04:32:33Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538202",
    "user": "https://github.com/videlec"
}
```

Changing branch from "" to "u/vdelecroix/28131"



---

archive/issue_comments_538203.json:
```json
{
    "body": "<a id='comment:2'></a>\nBranch pushed to git repo; I updated commit sha1. Last 10 new commits:\n|                                                                                                                                           |                               |\n|-------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------|\n|[13b0e3c](https://github.com/sagemath/sagetrac-mirror/commit/13b0e3cb46e61ec56c3271a3bce49b76ac6b8b36)|`Use libgap for direct_product`|\n|[6928f69](https://github.com/sagemath/sagetrac-mirror/commit/6928f6982e7a489d8e4c73c137bf052590cf4267)|`Use libgap for character_table`|\n|[77513fe](https://github.com/sagemath/sagetrac-mirror/commit/77513fee45213ebf297b59bbe7d43b4a24a6797c)|`Some fixes to make ClassFunction work properly with libgap.`|\n|[edf2a5d](https://github.com/sagemath/sagetrac-mirror/commit/edf2a5d7c595973e87389977b9a2abeaea9454dd)|`Use libgap for PermutationGroup_generic._regular_subgroup_gap`|\n|[6fbdbd1](https://github.com/sagemath/sagetrac-mirror/commit/6fbdbd1ae9afa5c5fd1b1caffa2c4b506b14c381)|`Use libgap for PermutationGroup_generic.molien_series`|\n|[42318a9](https://github.com/sagemath/sagetrac-mirror/commit/42318a9424b9b5b9d5332610232e113219420b3a)|`Fix minor test failure: This will now fail at trying to find a _libgap_init_ rather than a _gap_init_`|\n|[c02c2f1](https://github.com/sagemath/sagetrac-mirror/commit/c02c2f11a2c2228851419eb1aadd32fde75a2ad4)|`If the values passed to the ClassFunction constructor are already a libgap`|\n|[cc64910](https://github.com/sagemath/sagetrac-mirror/commit/cc6491009070408c9ed5dde6317ee0ac229458ca)|`Fixed slightly different output on a few tests due to PRNG differences related`|\n|[edebd67](https://github.com/sagemath/sagetrac-mirror/commit/edebd67e6e2c27e188cca51a05ea091479bcb6db)|`Merge branch 'u/embray/prototype/perm-gps-no-pexpect-gap' of trac.sagemath.org:sage into TMP10`|\n|[58793be](https://github.com/sagemath/sagetrac-mirror/commit/58793bead50dc08c46af7101379944c3ade5f7e3)|`28131: fix latte interface for py3`|",
    "created_at": "2019-07-08T04:32:36Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538203",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

<a id='comment:2'></a>
Branch pushed to git repo; I updated commit sha1. Last 10 new commits:
|                                                                                                                                           |                               |
|-------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------|
|[13b0e3c](https://github.com/sagemath/sagetrac-mirror/commit/13b0e3cb46e61ec56c3271a3bce49b76ac6b8b36)|`Use libgap for direct_product`|
|[6928f69](https://github.com/sagemath/sagetrac-mirror/commit/6928f6982e7a489d8e4c73c137bf052590cf4267)|`Use libgap for character_table`|
|[77513fe](https://github.com/sagemath/sagetrac-mirror/commit/77513fee45213ebf297b59bbe7d43b4a24a6797c)|`Some fixes to make ClassFunction work properly with libgap.`|
|[edf2a5d](https://github.com/sagemath/sagetrac-mirror/commit/edf2a5d7c595973e87389977b9a2abeaea9454dd)|`Use libgap for PermutationGroup_generic._regular_subgroup_gap`|
|[6fbdbd1](https://github.com/sagemath/sagetrac-mirror/commit/6fbdbd1ae9afa5c5fd1b1caffa2c4b506b14c381)|`Use libgap for PermutationGroup_generic.molien_series`|
|[42318a9](https://github.com/sagemath/sagetrac-mirror/commit/42318a9424b9b5b9d5332610232e113219420b3a)|`Fix minor test failure: This will now fail at trying to find a _libgap_init_ rather than a _gap_init_`|
|[c02c2f1](https://github.com/sagemath/sagetrac-mirror/commit/c02c2f11a2c2228851419eb1aadd32fde75a2ad4)|`If the values passed to the ClassFunction constructor are already a libgap`|
|[cc64910](https://github.com/sagemath/sagetrac-mirror/commit/cc6491009070408c9ed5dde6317ee0ac229458ca)|`Fixed slightly different output on a few tests due to PRNG differences related`|
|[edebd67](https://github.com/sagemath/sagetrac-mirror/commit/edebd67e6e2c27e188cca51a05ea091479bcb6db)|`Merge branch 'u/embray/prototype/perm-gps-no-pexpect-gap' of trac.sagemath.org:sage into TMP10`|
|[58793be](https://github.com/sagemath/sagetrac-mirror/commit/58793bead50dc08c46af7101379944c3ade5f7e3)|`28131: fix latte interface for py3`|



---

archive/issue_comments_538204.json:
```json
{
    "body": "Changing commit from \"\" to \"58793bead50dc08c46af7101379944c3ade5f7e3\"",
    "created_at": "2019-07-08T04:32:36Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538204",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

Changing commit from "" to "58793bead50dc08c46af7101379944c3ade5f7e3"



---

archive/issue_comments_538205.json:
```json
{
    "body": "<a id='comment:3'></a>\nBranch pushed to git repo; I updated commit sha1. This was a forced push. New commits:\n|                                                                                                                                           |                                    |\n|-------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------|\n|[579e9ef](https://github.com/sagemath/sagetrac-mirror/commit/579e9ef6c4cc66bfcbbc0fc79d5c68153335a561)|`28131: fix latte interface for py3`|",
    "created_at": "2019-07-08T04:34:21Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538205",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

<a id='comment:3'></a>
Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
|                                                                                                                                           |                                    |
|-------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------|
|[579e9ef](https://github.com/sagemath/sagetrac-mirror/commit/579e9ef6c4cc66bfcbbc0fc79d5c68153335a561)|`28131: fix latte interface for py3`|



---

archive/issue_comments_538206.json:
```json
{
    "body": "Changing commit from \"58793bead50dc08c46af7101379944c3ade5f7e3\" to \"579e9ef6c4cc66bfcbbc0fc79d5c68153335a561\"",
    "created_at": "2019-07-08T04:34:21Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538206",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

Changing commit from "58793bead50dc08c46af7101379944c3ade5f7e3" to "579e9ef6c4cc66bfcbbc0fc79d5c68153335a561"



---

archive/issue_comments_538207.json:
```json
{
    "body": "<a id='comment:4'></a>\nok, makes sense",
    "created_at": "2019-07-09T18:54:21Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538207",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:4'></a>
ok, makes sense



---

archive/issue_comments_538208.json:
```json
{
    "body": "Changing reviewer from \"\" to \"Fr\u00e9d\u00e9ric Chapoton\"",
    "created_at": "2019-07-09T18:54:21Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538208",
    "user": "https://github.com/fchapoton"
}
```

Changing reviewer from "" to "Frédéric Chapoton"



---

archive/issue_comments_538209.json:
```json
{
    "body": "Changing status from needs_review to positive_review.",
    "created_at": "2019-07-09T18:54:21Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538209",
    "user": "https://github.com/fchapoton"
}
```

Changing status from needs_review to positive_review.



---

archive/issue_events_086991.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2019-07-11T18:54:00Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/28131#event-86991"
}
```



---

archive/issue_comments_538210.json:
```json
{
    "body": "Changing branch from \"u/vdelecroix/28131\" to \"579e9ef6c4cc66bfcbbc0fc79d5c68153335a561\"",
    "created_at": "2019-07-11T18:54:00Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538210",
    "user": "https://github.com/vbraun"
}
```

Changing branch from "u/vdelecroix/28131" to "579e9ef6c4cc66bfcbbc0fc79d5c68153335a561"



---

archive/issue_comments_538211.json:
```json
{
    "body": "Resolution: fixed",
    "created_at": "2019-07-11T18:54:00Z",
    "issue": "https://github.com/sagemath/sagetest/issues/28131",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/28131#issuecomment-538211",
    "user": "https://github.com/vbraun"
}
```

Resolution: fixed
