# Issue 646: plot3d error on itanium

archive/issues_000646.json:
```json
{
    "assignees": [
        "https://github.com/robertwb"
    ],
    "body": "\n```\n---------- Forwarded message ----------\nFrom: Kate Minola <kate01123@gmail.com>\nDate: Sep 12, 2007 7:27 AM\nSubject: [sage-support] sage-2.8.4.1 build report\nTo: sage-support@googlegroups.com\n\n\n\nWilliam,\n\nsage-2.8.4.1 built and successfully passed all\ntests on the following architectures:\n\n  x86-Linux (pentium4-fc6)\n  x86_64-Linux (fc6)\n\nOn ia64-Linux, sage-2.8.4.1 only failed one test:\n      sage -t  devel/sage-main/sage/plot/plot3d/plot3d.py\n      [...]\n      File \"base.pyx\", line 274, in base.TransformGroup.get_transformation\n        self.T = Transformation(self._scale, self._rot, self._trans)\n      File \"transform.pyx\", line 37, in transform.Transformation.__init__\n        t = atan2(vy,vz) + pi/2\n    ValueError: math domain error\n\n```\n\nComponent: **packages: standard**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/646_\n\n",
    "closed_at": "2007-09-13T18:20:18Z",
    "created_at": "2007-09-13T05:42:53Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20packages%3A%20standard",
        "https://github.com/sagemath/sage/labels/p%3A%203%20%E2%80%93%20major",
        "https://github.com/sagemath/sage/labels/bug"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-2.8.4.2",
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "plot3d error on itanium",
    "type": "issue",
    "updated_at": "2007-09-13T18:20:18Z",
    "url": "https://github.com/sagemath/sage/issues/646",
    "user": "https://github.com/robertwb"
}
```

```
---------- Forwarded message ----------
From: Kate Minola <kate01123@gmail.com>
Date: Sep 12, 2007 7:27 AM
Subject: [sage-support] sage-2.8.4.1 build report
To: sage-support@googlegroups.com



William,

sage-2.8.4.1 built and successfully passed all
tests on the following architectures:

  x86-Linux (pentium4-fc6)
  x86_64-Linux (fc6)

On ia64-Linux, sage-2.8.4.1 only failed one test:
      sage -t  devel/sage-main/sage/plot/plot3d/plot3d.py
      [...]
      File "base.pyx", line 274, in base.TransformGroup.get_transformation
        self.T = Transformation(self._scale, self._rot, self._trans)
      File "transform.pyx", line 37, in transform.Transformation.__init__
        t = atan2(vy,vz) + pi/2
    ValueError: math domain error

```

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/646_





---

archive/issue_events_005856.json:
```json
{
    "actor": "https://github.com/robertwb",
    "created_at": "2007-09-13T05:42:53Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "milestone_number": null,
    "milestone_title": "sage-2.9",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5856"
}
```



---

archive/issue_events_005857.json:
```json
{
    "actor": "https://github.com/robertwb",
    "created_at": "2007-09-13T05:42:53Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20packages%3A%20standard",
    "label_color": "000080",
    "label_name": "c: packages: standard",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5857"
}
```



---

archive/issue_events_005858.json:
```json
{
    "actor": "https://github.com/robertwb",
    "created_at": "2007-09-13T05:42:53Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "label": "https://github.com/sagemath/sage/labels/p%3A%203%20%E2%80%93%20major",
    "label_color": "ffbb00",
    "label_name": "p: 3 \u2013 major",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5858"
}
```



---

archive/issue_events_005859.json:
```json
{
    "actor": "https://github.com/robertwb",
    "created_at": "2007-09-13T05:42:53Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5859"
}
```



---

archive/issue_events_005860.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2007-09-13T05:42:53Z",
    "event": "assigned",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "subject": "https://github.com/robertwb",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5860"
}
```



---

archive/issue_comments_002273.json:
```json
{
    "body": "Attachment: **[itanium-atan2.patch.gz](https://github.com/sagemath/sage/files/ticket646/itanium-atan2.patch.gz)**",
    "created_at": "2007-09-13T05:43:35Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/646#issuecomment-2273",
    "user": "https://github.com/robertwb"
}
```

Attachment: **[itanium-atan2.patch.gz](https://github.com/sagemath/sage/files/ticket646/itanium-atan2.patch.gz)**



---

archive/issue_comments_002274.json:
```json
{
    "body": "<div id=\"comment:1\" align=\"right\">comment:1</div>\n\nLooks like itanium sets errno on atan2(0,0), whereas other processors\nreturn 0. Here's a fix.\n\nI am going to rewrite the function to be cleaner and avoid all use of atan.",
    "created_at": "2007-09-13T05:47:07Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/646#issuecomment-2274",
    "user": "https://github.com/robertwb"
}
```

<div id="comment:1" align="right">comment:1</div>

Looks like itanium sets errno on atan2(0,0), whereas other processors
return 0. Here's a fix.

I am going to rewrite the function to be cleaner and avoid all use of atan.



---

archive/issue_events_005861.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2007-09-13T05:47:07Z",
    "event": "unassigned",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "subject": "https://github.com/robertwb",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5861"
}
```



---

archive/issue_events_005862.json:
```json
{
    "actor": "https://github.com/robertwb",
    "created_at": "2007-09-13T05:47:07Z",
    "event": "assigned",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "subject": "https://github.com/robertwb",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5862"
}
```



---

archive/issue_events_005863.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2007-09-13T06:20:36Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "milestone_number": null,
    "milestone_title": "sage-2.9",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5863"
}
```



---

archive/issue_events_005864.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2007-09-13T06:20:36Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "milestone_number": null,
    "milestone_title": "sage-2.8.4.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5864"
}
```



---

archive/issue_events_005865.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2007-09-13T06:20:36Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5865"
}
```



---

archive/issue_comments_002275.json:
```json
{
    "body": "<div id=\"comment:3\" align=\"right\">comment:3</div>\n\nStill broken:\n\n```\nWilliam,\n\nThe patch as written gives the same error.  However if you\nchange line 37 of the patch from\n    if vx == vy == 0:\nto\n    if vy == vz == 0:\n(since atan2() is taking arguments vy and vz) then\nI get a different error on ia64-Linux:\n\nsage -t  devel/sage-main/sage/plot/plot3d/plot3d.py\n**********************************************************************\nFile \"plot3d.py\", line 19:\n   sage: S.show()\nExpected nothing\nGot:\n   6.0\n   <type 'sage.rings.real_double.RealDoubleElement'>\n   0.0\n   0.0\n**********************************************************************\n```",
    "created_at": "2007-09-13T15:52:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/646#issuecomment-2275",
    "user": "https://github.com/williamstein"
}
```

<div id="comment:3" align="right">comment:3</div>

Still broken:

```
William,

The patch as written gives the same error.  However if you
change line 37 of the patch from
    if vx == vy == 0:
to
    if vy == vz == 0:
(since atan2() is taking arguments vy and vz) then
I get a different error on ia64-Linux:

sage -t  devel/sage-main/sage/plot/plot3d/plot3d.py
**********************************************************************
File "plot3d.py", line 19:
   sage: S.show()
Expected nothing
Got:
   6.0
   <type 'sage.rings.real_double.RealDoubleElement'>
   0.0
   0.0
**********************************************************************
```



---

archive/issue_events_005866.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2007-09-13T15:52:32Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "milestone_number": null,
    "milestone_title": "sage-2.8.4.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5866"
}
```



---

archive/issue_events_005867.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2007-09-13T15:52:32Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "milestone_number": null,
    "milestone_title": "sage-2.8.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5867"
}
```



---

archive/issue_comments_002276.json:
```json
{
    "body": "<div id=\"comment:5\" align=\"right\">comment:5</div>\n\nAttachment: **[better-plot3d-rot.patch.gz](https://github.com/sagemath/sage/files/ticket646/better-plot3d-rot.patch.gz)**\n\nHopefully this is not fixed (it's in 2.8.4.2)",
    "created_at": "2007-09-13T18:20:18Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/646#issuecomment-2276",
    "user": "https://github.com/williamstein"
}
```

<div id="comment:5" align="right">comment:5</div>

Attachment: **[better-plot3d-rot.patch.gz](https://github.com/sagemath/sage/files/ticket646/better-plot3d-rot.patch.gz)**

Hopefully this is not fixed (it's in 2.8.4.2)



---

archive/issue_events_005868.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2007-09-13T18:20:18Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "milestone_number": null,
    "milestone_title": "sage-2.8.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5868"
}
```



---

archive/issue_events_005869.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2007-09-13T18:20:18Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "milestone_number": null,
    "milestone_title": "sage-2.8.4.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5869"
}
```



---

archive/issue_events_005870.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2007-09-13T18:20:18Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/646",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/646#event-5870"
}
```
