# Issue 22834: infinite recursion in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__

archive/issues_022597.json:
```json
{
    "assignees": [],
    "body": "Division by zero in `CIF` leads to infinite recursion:\n\n```\nsage: ~CIF(RIF(-1,1))\n---------------------------------------------------------------------------\nRuntimeError                              Traceback (most recent call last)\n<ipython-input-4-7c8464c26127> in <module>()\n----> 1 ~CIF(RIF(-Integer(1),Integer(1)))\n\n/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()\n   1290             return -I*(-I*self).__invert__()\n   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n-> 1292             return -(-self).__invert__()\n   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first\n   1294             I = self.parent().gen(0)\n\n... last 1 frames repeated, from the frame below ...\n\n/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()\n   1290             return -I*(-I*self).__invert__()\n   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n-> 1292             return -(-self).__invert__()\n   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first\n   1294             I = self.parent().gen(0)\n\nRuntimeError: maximum recursion depth exceeded while calling a Python object\n```\n\nThe bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):\n\n```\n        elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n            return -(-self).__invert__()\n```\n\nwhich looks like it can fail in that way if the signs are zero.\n\nMinor additional comment: `foo.__invert__()` should be replaced by `~foo` which is faster.\n\nCC:  @miguelmarco\n\nComponent: **basic arithmetic**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/22834_\n\n",
    "created_at": "2017-04-19T18:44:52Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20basic%20arithmetic",
        "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
        "https://github.com/sagemath/sage/labels/bug"
    ],
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "infinite recursion in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__",
    "type": "issue",
    "updated_at": "2022-12-29T01:39:18Z",
    "url": "https://github.com/sagemath/sage/issues/22834",
    "user": "https://github.com/sagetrac-wonder"
}
```
Division by zero in `CIF` leads to infinite recursion:

```
sage: ~CIF(RIF(-1,1))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-7c8464c26127> in <module>()
----> 1 ~CIF(RIF(-Integer(1),Integer(1)))

/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()
   1290             return -I*(-I*self).__invert__()
   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
-> 1292             return -(-self).__invert__()
   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first
   1294             I = self.parent().gen(0)

... last 1 frames repeated, from the frame below ...

/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()
   1290             return -I*(-I*self).__invert__()
   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
-> 1292             return -(-self).__invert__()
   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first
   1294             I = self.parent().gen(0)

RuntimeError: maximum recursion depth exceeded while calling a Python object
```

The bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):

```
        elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
            return -(-self).__invert__()
```

which looks like it can fail in that way if the signs are zero.

Minor additional comment: `foo.__invert__()` should be replaced by `~foo` which is faster.

CC:  @miguelmarco

Component: **basic arithmetic**

_Issue created by migration from https://trac.sagemath.org/ticket/22834_





---

archive/issue_events_315856.json:
```json
{
    "actor": "https://github.com/sagetrac-wonder",
    "created_at": "2017-04-19T18:44:52Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20number%20fields",
    "label_color": "0000ff",
    "label_name": "c: number fields",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22834#event-315856"
}
```



---

archive/issue_events_315857.json:
```json
{
    "actor": "https://github.com/sagetrac-wonder",
    "created_at": "2017-04-19T18:44:52Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
    "label_color": "ffbb00",
    "label_name": "p: major / 3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22834#event-315857"
}
```



---

archive/issue_events_315858.json:
```json
{
    "actor": "https://github.com/sagetrac-wonder",
    "created_at": "2017-04-19T18:44:52Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22834#event-315858"
}
```



---

archive/issue_comments_340434.json:
```json
{
    "body": "<div id=\"comment:1\" align=\"right\">comment:1</div>\n\nCalling N() before comparing to zero seems to be a usable workaround",
    "created_at": "2017-04-19T18:48:14Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22834#issuecomment-340434",
    "user": "https://github.com/sagetrac-wonder"
}
```

<div id="comment:1" align="right">comment:1</div>

Calling N() before comparing to zero seems to be a usable workaround



---

archive/issue_comments_340435.json:
```json
{
    "body": "<div id=\"comment:2\" align=\"right\">comment:2</div>\n\nDo you have a complete example?",
    "created_at": "2017-04-20T08:46:40Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22834#issuecomment-340435",
    "user": "https://github.com/jdemeyer"
}
```

<div id="comment:2" align="right">comment:2</div>

Do you have a complete example?



---

archive/issue_comments_340436.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -1,13 +1,32 @@\n-It is possible to crash sage with an infinite recursion by comparing a number to zero:\n+Division by zero in `CIF` leads to infinite recursion:\n \n ```\n-...\n-  File \"sage/rings/complex_interval.pyx\", line 1287, in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (/builddir/build/BUILD/sage-7.3/src/build/cythonized/sage/rings/complex_interval.c:13434)\n-  File \"sage/rings/complex_interval.pyx\", line 1287, in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (/builddir/build/BUILD/sage-7.3/src/build/cythonized/sage/rings/complex_interval.c:13434)\n+sage: ~CIF(RIF(-1,1))\n+---------------------------------------------------------------------------\n+RuntimeError                              Traceback (most recent call last)\n+<ipython-input-4-7c8464c26127> in <module>()\n+----> 1 ~CIF(RIF(-Integer(1),Integer(1)))\n+\n+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()\n+   1290             return -I*(-I*self).__invert__()\n+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n+-> 1292             return -(-self).__invert__()\n+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first\n+   1294             I = self.parent().gen(0)\n+\n+... last 1 frames repeated, from the frame below ...\n+\n+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()\n+   1290             return -I*(-I*self).__invert__()\n+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n+-> 1292             return -(-self).__invert__()\n+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first\n+   1294             I = self.parent().gen(0)\n+\n RuntimeError: maximum recursion depth exceeded while calling a Python object\n ```\n \n-It looks like this came up in my code when comparing an algebraic number to zero, but the bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):\n+The bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):\n \n ```\n         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth\n``````\n",
    "created_at": "2017-04-20T08:51:02Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22834#issuecomment-340436",
    "user": "https://github.com/jdemeyer"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -1,13 +1,32 @@
-It is possible to crash sage with an infinite recursion by comparing a number to zero:
+Division by zero in `CIF` leads to infinite recursion:
 
 ```
-...
-  File "sage/rings/complex_interval.pyx", line 1287, in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (/builddir/build/BUILD/sage-7.3/src/build/cythonized/sage/rings/complex_interval.c:13434)
-  File "sage/rings/complex_interval.pyx", line 1287, in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (/builddir/build/BUILD/sage-7.3/src/build/cythonized/sage/rings/complex_interval.c:13434)
+sage: ~CIF(RIF(-1,1))
+---------------------------------------------------------------------------
+RuntimeError                              Traceback (most recent call last)
+<ipython-input-4-7c8464c26127> in <module>()
+----> 1 ~CIF(RIF(-Integer(1),Integer(1)))
+
+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()
+   1290             return -I*(-I*self).__invert__()
+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
+-> 1292             return -(-self).__invert__()
+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first
+   1294             I = self.parent().gen(0)
+
+... last 1 frames repeated, from the frame below ...
+
+/usr/local/src/sage-config/src/sage/rings/complex_interval.pyx in sage.rings.complex_interval.ComplexIntervalFieldElement.__invert__ (build/cythonized/sage/rings/complex_interval.c:13416)()
+   1290             return -I*(-I*self).__invert__()
+   1291         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
+-> 1292             return -(-self).__invert__()
+   1293         elif mpfr_sgn(a) >=0: #fourth or between fourth and first
+   1294             I = self.parent().gen(0)
+
 RuntimeError: maximum recursion depth exceeded while calling a Python object
 ```
 
-It looks like this came up in my code when comparing an algebraic number to zero, but the bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):
+The bug appears to trace to this code at `sage/rings/complex_interval.pyx`, line 1287 (SageMath version 7.3, Release Date: 2016-08-04):
 
 ```
         elif mpfr_sgn(a) <= 0 and mpfr_sgn(d) <= 0: # thirthd quadrant or between thirthd and fourth
``````




---

archive/issue_events_315859.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-04-20T08:51:02Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "milestone_number": null,
    "milestone_title": "sage-8.0",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22834#event-315859"
}
```



---

archive/issue_events_315860.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-04-20T08:51:02Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20number%20fields",
    "label_color": "0000ff",
    "label_name": "c: number fields",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22834#event-315860"
}
```



---

archive/issue_events_315861.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-04-20T08:51:02Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20basic%20arithmetic",
    "label_color": "0000ff",
    "label_name": "c: basic arithmetic",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22834#event-315861"
}
```



---

archive/issue_comments_340437.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -35,3 +35,4 @@\n \n which looks like it can fail in that way if the signs are zero.\n \n+Minor additional comment: `foo.__invert__()` should be replaced by `~foo` which is faster.\n``````\n",
    "created_at": "2017-04-20T08:53:43Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22834#issuecomment-340437",
    "user": "https://github.com/jdemeyer"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -35,3 +35,4 @@
 
 which looks like it can fail in that way if the signs are zero.
 
+Minor additional comment: `foo.__invert__()` should be replaced by `~foo` which is faster.
``````




---

archive/issue_comments_340438.json:
```json
{
    "body": "<div id=\"comment:5\" align=\"right\">comment:5</div>\n\nWorks now\n\n```\n\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510\n\u2502 SageMath version 9.1.rc4, Release Date: 2020-05-09                 \u2502\n\u2502 Using Python 3.7.3. Type \"help()\" for help.                        \u2502\n\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518\n\u250f\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2513\n\u2503 Warning: this is a prerelease version, and it may be unstable.     \u2503\n\u2517\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u251b\nsage: ~CIF(RIF(-1,1))\n[.. NaN ..] + [.. NaN ..]*I\n```",
    "created_at": "2020-05-13T15:37:27Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22834#issuecomment-340438",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:5" align="right">comment:5</div>

Works now

```
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.1.rc4, Release Date: 2020-05-09                 │
│ Using Python 3.7.3. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
sage: ~CIF(RIF(-1,1))
[.. NaN ..] + [.. NaN ..]*I
```



---

archive/issue_events_315862.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-12-29T01:39:18Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/22834",
    "milestone_number": null,
    "milestone_title": "sage-8.0",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22834#event-315862"
}
```
