# Issue 24698: fixing one plantri doctest

archive/issues_024461.json:
```json
{
    "assignees": [],
    "body": "Future division made a doctest failure with the optional package plantri installed\n\n```\nsage -t --long src/sage/graphs/graph_generators.py\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1408, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    [u for u in list(gen)]  # optional plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>\", line 1, in <module>\n        [u for u in list(gen)]  # optional plantri\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n        for G in graphs._read_planar_code(sp.stdout):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n        edges_g[i + 1] += [i + 1] * (Ni / 2)\n    TypeError: can't multiply sequence by non-int of type 'float'\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1439, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>\", line 1, in <module>\n        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n        for G in graphs._read_planar_code(sp.stdout):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n        edges_g[i + 1] += [i + 1] * (Ni / 2)\n    TypeError: can't multiply sequence by non-int of type 'float'\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1441, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar_sizes      = [g.size() for g in planar]         # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>\", line 1, in <module>\n        planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n    NameError: name 'planar' is not defined\n**********************************************************************\nFile \"src/sage/graphs/graph_generators.py\", line 1443, in sage.graphs.graph_generators.GraphGenerators.?\nFailed example:\n    planar_sizes == dual_planar_sizes                      # optional -- plantri\nException raised:\n    Traceback (most recent call last):\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>\", line 1, in <module>\n        planar_sizes == dual_planar_sizes                      # optional -- plantri\n    NameError: name 'planar_sizes' is not defined\n**********************************************************************\n1 item had failures:\n   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?\n    [140 tests, 4 failures, 29.80 s]\n```\n\n**CC:**  @tscrim @embray @jdemeyer\n\n**Branch/Commit:** [a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)\n\n**Reviewer:** Travis Scrimshaw\n\n**Author:** Fr\u00e9d\u00e9ric Chapoton\n\nIssue created by migration from https://trac.sagemath.org/ticket/24698\n\n",
    "closed_at": "2018-02-16T23:39:03Z",
    "created_at": "2018-02-09T16:52:43Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/component%3A%20graph%20theory",
        "https://github.com/sagemath/sage/labels/blocker",
        "https://github.com/sagemath/sage/labels/enhancement"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-8.2",
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "fixing one plantri doctest",
    "type": "issue",
    "updated_at": "2018-02-16T23:39:03Z",
    "url": "https://github.com/sagemath/sage/issues/24698",
    "user": "https://github.com/fchapoton"
}
```
Future division made a doctest failure with the optional package plantri installed

```
sage -t --long src/sage/graphs/graph_generators.py
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1408, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    [u for u in list(gen)]  # optional plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>", line 1, in <module>
        [u for u in list(gen)]  # optional plantri
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
        for G in graphs._read_planar_code(sp.stdout):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
        edges_g[i + 1] += [i + 1] * (Ni / 2)
    TypeError: can't multiply sequence by non-int of type 'float'
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1439, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>", line 1, in <module>
        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
        for G in graphs._read_planar_code(sp.stdout):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
        edges_g[i + 1] += [i + 1] * (Ni / 2)
    TypeError: can't multiply sequence by non-int of type 'float'
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1441, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar_sizes      = [g.size() for g in planar]         # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>", line 1, in <module>
        planar_sizes      = [g.size() for g in planar]         # optional -- plantri
    NameError: name 'planar' is not defined
**********************************************************************
File "src/sage/graphs/graph_generators.py", line 1443, in sage.graphs.graph_generators.GraphGenerators.?
Failed example:
    planar_sizes == dual_planar_sizes                      # optional -- plantri
Exception raised:
    Traceback (most recent call last):
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>", line 1, in <module>
        planar_sizes == dual_planar_sizes                      # optional -- plantri
    NameError: name 'planar_sizes' is not defined
**********************************************************************
1 item had failures:
   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?
    [140 tests, 4 failures, 29.80 s]
```

**CC:**  @tscrim @embray @jdemeyer

**Branch/Commit:** [a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)

**Reviewer:** Travis Scrimshaw

**Author:** Frédéric Chapoton

Issue created by migration from https://trac.sagemath.org/ticket/24698





---

archive/issue_events_297693.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "milestone_number": null,
    "milestone_title": "sage-8.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297693"
}
```



---

archive/issue_events_297694.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/component%3A%20graph%20theory",
    "label_color": "08517b",
    "label_name": "component: graph theory",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297694"
}
```



---

archive/issue_events_297695.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:52:43Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/enhancement",
    "label_color": "008080",
    "label_name": "enhancement",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297695"
}
```



---

archive/issue_comments_377908.json:
```json
{
    "body": "**Branch:** [u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)",
    "created_at": "2018-02-09T16:53:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377908",
    "user": "https://github.com/fchapoton"
}
```

**Branch:** [u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)



---

archive/issue_events_297696.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-02-09T16:53:26Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "008080",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297696"
}
```



---

archive/issue_comments_377909.json:
```json
{
    "body": "<a id='comment:1'>**Comment 1:**</a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc\">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>\n",
    "created_at": "2018-02-09T16:53:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377909",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:1'>**Comment 1:**</a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>




---

archive/issue_comments_377910.json:
```json
{
    "body": "**Commit:** [a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)",
    "created_at": "2018-02-09T16:53:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377910",
    "user": "https://github.com/fchapoton"
}
```

**Commit:** [a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)



---

archive/issue_events_297697.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-09T21:41:10Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "008080",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297697"
}
```



---

archive/issue_events_297698.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-09T21:41:10Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "008080",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297698"
}
```



---

archive/issue_comments_377911.json:
```json
{
    "body": "<a id='comment:2'>**Comment 2:**</a>\nLGTM.",
    "created_at": "2018-02-09T21:41:10Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377911",
    "user": "https://github.com/tscrim"
}
```

<a id='comment:2'>**Comment 2:**</a>
LGTM.



---

archive/issue_comments_377912.json:
```json
{
    "body": "**Reviewer:** Travis Scrimshaw",
    "created_at": "2018-02-09T21:41:10Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377912",
    "user": "https://github.com/tscrim"
}
```

**Reviewer:** Travis Scrimshaw



---

archive/issue_events_297699.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-02-09T23:50:46Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "008080",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297699"
}
```



---

archive/issue_events_297700.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-02-09T23:50:46Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "008080",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297700"
}
```



---

archive/issue_comments_377913.json:
```json
{
    "body": "<a id='comment:3'>**Comment 3:**</a>\nMerge conflict",
    "created_at": "2018-02-09T23:50:46Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377913",
    "user": "https://github.com/vbraun"
}
```

<a id='comment:3'>**Comment 3:**</a>
Merge conflict



---

archive/issue_comments_377914.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -1 +1,69 @@\n-coming from future division\n+Future division made a doctest failure with the optional package plantri installed\n+\n+```\n+sage -t --long src/sage/graphs/graph_generators.py\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1408, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    [u for u in list(gen)]  # optional plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>\", line 1, in <module>\n+        [u for u in list(gen)]  # optional plantri\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n+        for G in graphs._read_planar_code(sp.stdout):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n+        edges_g[i + 1] += [i + 1] * (Ni / 2)\n+    TypeError: can't multiply sequence by non-int of type 'float'\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1439, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>\", line 1, in <module>\n+        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1527, in planar_graphs\n+        for G in graphs._read_planar_code(sp.stdout):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py\", line 1122, in _read_planar_code\n+        edges_g[i + 1] += [i + 1] * (Ni / 2)\n+    TypeError: can't multiply sequence by non-int of type 'float'\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1441, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>\", line 1, in <module>\n+        planar_sizes      = [g.size() for g in planar]         # optional -- plantri\n+    NameError: name 'planar' is not defined\n+**********************************************************************\n+File \"src/sage/graphs/graph_generators.py\", line 1443, in sage.graphs.graph_generators.GraphGenerators.?\n+Failed example:\n+    planar_sizes == dual_planar_sizes                      # optional -- plantri\n+Exception raised:\n+    Traceback (most recent call last):\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 534, in _run\n+        self.compile_and_execute(example, compiler, test.globs)\n+      File \"/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 937, in compile_and_execute\n+        exec(compiled, globs)\n+      File \"<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>\", line 1, in <module>\n+        planar_sizes == dual_planar_sizes                      # optional -- plantri\n+    NameError: name 'planar_sizes' is not defined\n+**********************************************************************\n+1 item had failures:\n+   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?\n+    [140 tests, 4 failures, 29.80 s]\n+```\n``````\n",
    "created_at": "2018-02-13T19:23:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377914",
    "user": "https://github.com/videlec"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -1 +1,69 @@
-coming from future division
+Future division made a doctest failure with the optional package plantri installed
+
+```
+sage -t --long src/sage/graphs/graph_generators.py
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1408, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    [u for u in list(gen)]  # optional plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[5]>", line 1, in <module>
+        [u for u in list(gen)]  # optional plantri
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
+        for G in graphs._read_planar_code(sp.stdout):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
+        edges_g[i + 1] += [i + 1] * (Ni / 2)
+    TypeError: can't multiply sequence by non-int of type 'float'
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1439, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar      = list(graphs.planar_graphs(5,dual=True))  # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[10]>", line 1, in <module>
+        planar      = list(graphs.planar_graphs(Integer(5),dual=True))  # optional -- plantri
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1527, in planar_graphs
+        for G in graphs._read_planar_code(sp.stdout):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/graphs/graph_generators.py", line 1122, in _read_planar_code
+        edges_g[i + 1] += [i + 1] * (Ni / 2)
+    TypeError: can't multiply sequence by non-int of type 'float'
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1441, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar_sizes      = [g.size() for g in planar]         # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[12]>", line 1, in <module>
+        planar_sizes      = [g.size() for g in planar]         # optional -- plantri
+    NameError: name 'planar' is not defined
+**********************************************************************
+File "src/sage/graphs/graph_generators.py", line 1443, in sage.graphs.graph_generators.GraphGenerators.?
+Failed example:
+    planar_sizes == dual_planar_sizes                      # optional -- plantri
+Exception raised:
+    Traceback (most recent call last):
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 534, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/home/vdelecro/sage_patchbot/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 937, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.graphs.graph_generators.GraphGenerators.?[14]>", line 1, in <module>
+        planar_sizes == dual_planar_sizes                      # optional -- plantri
+    NameError: name 'planar_sizes' is not defined
+**********************************************************************
+1 item had failures:
+   4 of  38 in sage.graphs.graph_generators.GraphGenerators.?
+    [140 tests, 4 failures, 29.80 s]
+```
``````




---

archive/issue_events_297701.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-13T19:23:25Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/blocker",
    "label_color": "ff0000",
    "label_name": "blocker",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297701"
}
```



---

archive/issue_comments_377915.json:
```json
{
    "body": "<a id='comment:5'>**Comment 5:**</a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834\">d910d87</a></td><td><code>fix a division in graph_generators.py</code></td></tr></table>\n",
    "created_at": "2018-02-14T17:57:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377915",
    "user": "https://github.com/videlec"
}
```

<a id='comment:5'>**Comment 5:**</a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834">d910d87</a></td><td><code>fix a division in graph_generators.py</code></td></tr></table>




---

archive/issue_comments_377916.json:
```json
{
    "body": "**Changing commit** from \"[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)\" to \"[d910d879adc9975475cd3f9fa385aeccada33834](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)\".",
    "created_at": "2018-02-14T17:57:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377916",
    "user": "https://github.com/videlec"
}
```

**Changing commit** from "[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)" to "[d910d879adc9975475cd3f9fa385aeccada33834](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)".



---

archive/issue_events_297702.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:25Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "008080",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297702"
}
```



---

archive/issue_events_297703.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:25Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "008080",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297703"
}
```



---

archive/issue_comments_377917.json:
```json
{
    "body": "**Changing branch** from \"[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)\" to \"[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)\".",
    "created_at": "2018-02-14T17:57:25Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377917",
    "user": "https://github.com/videlec"
}
```

**Changing branch** from "[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)" to "[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)".



---

archive/issue_events_297704.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:48Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "008080",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297704"
}
```



---

archive/issue_events_297705.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:57:48Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "008080",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297705"
}
```



---

archive/issue_comments_377918.json:
```json
{
    "body": "**Changing commit** from \"[d910d879adc9975475cd3f9fa385aeccada33834](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)\" to \"[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)\".",
    "created_at": "2018-02-14T17:58:29Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377918",
    "user": "https://github.com/videlec"
}
```

**Changing commit** from "[d910d879adc9975475cd3f9fa385aeccada33834](https://github.com/sagemath/sagetrac-mirror/commit/d910d879adc9975475cd3f9fa385aeccada33834)" to "[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)".



---

archive/issue_comments_377919.json:
```json
{
    "body": "<a id='comment:7'>**Comment 7:**</a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc\">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>\n",
    "created_at": "2018-02-14T17:58:29Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377919",
    "user": "https://github.com/videlec"
}
```

<a id='comment:7'>**Comment 7:**</a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc">a09e8a6</a></td><td><code>fixing one plantri doctest</code></td></tr></table>




---

archive/issue_events_297706.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:58:29Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "008080",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297706"
}
```



---

archive/issue_events_297707.json:
```json
{
    "actor": "https://github.com/videlec",
    "created_at": "2018-02-14T17:58:29Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "008080",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297707"
}
```



---

archive/issue_comments_377920.json:
```json
{
    "body": "**Changing branch** from \"[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)\" to \"[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)\".",
    "created_at": "2018-02-14T17:58:29Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377920",
    "user": "https://github.com/videlec"
}
```

**Changing branch** from "[u/vdelecroix/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/vdelecroix/24698)" to "[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)".



---

archive/issue_comments_377921.json:
```json
{
    "body": "<a id='comment:8'>**Comment 8:**</a>\nReplying to [@vbraun](#comment%3A3):\n> Merge conflict\n\nSince this is fixing doctest related to an optional package, it would be nice to get it merged in the next beta...",
    "created_at": "2018-02-14T17:59:20Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377921",
    "user": "https://github.com/videlec"
}
```

<a id='comment:8'>**Comment 8:**</a>
Replying to [@vbraun](#comment%3A3):
> Merge conflict

Since this is fixing doctest related to an optional package, it would be nice to get it merged in the next beta...



---

archive/issue_comments_377922.json:
```json
{
    "body": "<a id='comment:9'>**Comment 9:**</a>\nIt is supposed to have a conflict with Volker's private branch. But looking at the file there:\n\nhttps://github.com/vbraun/sage/commits/develop/src/sage/graphs/graph_generators.py\n\nI really do not see how there could be any conflict. This file was last modified 3 weeks ago.",
    "created_at": "2018-02-14T18:41:45Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377922",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:9'>**Comment 9:**</a>
It is supposed to have a conflict with Volker's private branch. But looking at the file there:

https://github.com/vbraun/sage/commits/develop/src/sage/graphs/graph_generators.py

I really do not see how there could be any conflict. This file was last modified 3 weeks ago.



---

archive/issue_events_297708.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-14T22:46:54Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "008080",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297708"
}
```



---

archive/issue_events_297709.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-02-14T22:46:54Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "008080",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297709"
}
```



---

archive/issue_comments_377923.json:
```json
{
    "body": "<a id='comment:10'>**Comment 10:**</a>\nLet's try it again then.",
    "created_at": "2018-02-14T22:46:54Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377923",
    "user": "https://github.com/tscrim"
}
```

<a id='comment:10'>**Comment 10:**</a>
Let's try it again then.



---

archive/issue_events_297710.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-02-16T23:39:03Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "008080",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297710"
}
```



---

archive/issue_events_297711.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "d7195f1f358f0bbd7424a7c809914e0d144a43dc",
    "commit_repository": "https://github.com/sagemath/sage",
    "created_at": "2018-02-16T23:39:03Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24698#event-297711"
}
```



---

archive/issue_comments_377924.json:
```json
{
    "body": "**Changing branch** from \"[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)\" to \"[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)\".",
    "created_at": "2018-02-16T23:39:03Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24698",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24698#issuecomment-377924",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/chapoton/24698](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/24698)" to "[a09e8a63476b3595b65308afb0acb704cb77bedc](https://github.com/sagemath/sagetrac-mirror/commit/a09e8a63476b3595b65308afb0acb704cb77bedc)".
