# Issue 3816: [with patch, positive review] notebook -- SyntaxWarning in twist.py

archive/issues_003816.json:
```json
{
    "body": "this was in there forever, but for some reason it causes a warning...\n\nFrom Cremona:\n\n```\n\nI have a successful build of 3.1.alpha1.  When I make a clone, the\n*first* time I run sage (by typing ./sage in SAGE_ROOT right after the\nsage -clone) I get this message after the banner and before the first\nprompt:\n\n/home/john/sage-3.1.alpha1/local/lib/python2.5/site-packages/sage/server/notebook/twist.py:1762:\nSyntaxWarning: name 'notebook' is used prior to global declaration\n global notebook\n\nBut if I then quit and restart, the message does not recur.\n\nWhat gives?\n\nJohn\n\n```\n\nAssignee: boothby\n\nResolution: fixed\n\nIssue created by migration from https://trac.sagemath.org/ticket/3816\n\n",
    "closed_at": "2008-08-13T06:39:15Z",
    "created_at": "2008-08-12T13:16:44Z",
    "labels": [
        "component: notebook",
        "blocker",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sagetest/milestones/sage-3.1",
    "title": "[with patch, positive review] notebook -- SyntaxWarning in twist.py",
    "type": "issue",
    "url": "https://github.com/sagemath/sagetest/issues/3816",
    "user": "https://github.com/williamstein"
}
```
this was in there forever, but for some reason it causes a warning...

From Cremona:

```

I have a successful build of 3.1.alpha1.  When I make a clone, the
*first* time I run sage (by typing ./sage in SAGE_ROOT right after the
sage -clone) I get this message after the banner and before the first
prompt:

/home/john/sage-3.1.alpha1/local/lib/python2.5/site-packages/sage/server/notebook/twist.py:1762:
SyntaxWarning: name 'notebook' is used prior to global declaration
 global notebook

But if I then quit and restart, the message does not recur.

What gives?

John

```

Assignee: boothby

Resolution: fixed

Issue created by migration from https://trac.sagemath.org/ticket/3816





---

archive/issue_comments_028589.json:
```json
{
    "body": "Attachment [sage-3816.patch](tarball://root/attachments/some-uuid/ticket3816/sage-3816.patch) by @williamstein created at 2008-08-12 13:17:10",
    "created_at": "2008-08-12T13:17:10Z",
    "issue": "https://github.com/sagemath/sagetest/issues/3816",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/3816#issuecomment-28589",
    "user": "https://github.com/williamstein"
}
```

Attachment [sage-3816.patch](tarball://root/attachments/some-uuid/ticket3816/sage-3816.patch) by @williamstein created at 2008-08-12 13:17:10



---

archive/issue_comments_028590.json:
```json
{
    "body": "<a id='comment:1'></a>\nPositive review. Patch looks good to me.\n\nCheers,\n\nMichael",
    "created_at": "2008-08-13T06:38:26Z",
    "issue": "https://github.com/sagemath/sagetest/issues/3816",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/3816#issuecomment-28590",
    "user": "https://trac.sagemath.org/admin/accounts/users/mabshoff"
}
```

<a id='comment:1'></a>
Positive review. Patch looks good to me.

Cheers,

Michael



---

archive/issue_events_014130.json:
```json
{
    "event": "renamed",
    "issue": "https://github.com/sagemath/sagetest/issues/3816",
    "rename": {
        "from": "[with patch; needs review] notebook -- SyntaxWarning in twist.py",
        "to": "[with patch, positive review] notebook -- SyntaxWarning in twist.py"
    },
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/3816#event-14130"
}
```



---

archive/issue_comments_028591.json:
```json
{
    "body": "Resolution: fixed",
    "created_at": "2008-08-13T06:39:15Z",
    "issue": "https://github.com/sagemath/sagetest/issues/3816",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/3816#issuecomment-28591",
    "user": "https://trac.sagemath.org/admin/accounts/users/mabshoff"
}
```

Resolution: fixed



---

archive/issue_events_014131.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/mabshoff",
    "created_at": "2008-08-13T06:39:15Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sagetest/issues/3816",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sagetest/issues/3816#event-14131"
}
```



---

archive/issue_comments_028592.json:
```json
{
    "body": "<a id='comment:2'></a>\nMerged in Sage 3.1.alpha2",
    "created_at": "2008-08-13T06:39:15Z",
    "issue": "https://github.com/sagemath/sagetest/issues/3816",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sagetest/issues/3816#issuecomment-28592",
    "user": "https://trac.sagemath.org/admin/accounts/users/mabshoff"
}
```

<a id='comment:2'></a>
Merged in Sage 3.1.alpha2
