# Issue 3816: notebook -- SyntaxWarning in twist.py

archive/issues_003816.json:
```json
{
    "assignees": [
        "https://github.com/boothby"
    ],
    "body": "this was in there forever, but for some reason it causes a warning...\n\nFrom Cremona:\n\n```\n\nI have a successful build of 3.1.alpha1.  When I make a clone, the\n*first* time I run sage (by typing ./sage in SAGE_ROOT right after the\nsage -clone) I get this message after the banner and before the first\nprompt:\n\n/home/john/sage-3.1.alpha1/local/lib/python2.5/site-packages/sage/server/notebook/twist.py:1762:\nSyntaxWarning: name 'notebook' is used prior to global declaration\n global notebook\n\nBut if I then quit and restart, the message does not recur.\n\nWhat gives?\n\nJohn\n\n```\n\nComponent: **notebook**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/3816_\n\n",
    "closed_at": "2008-08-13T06:39:15Z",
    "created_at": "2008-08-12T13:16:44Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20user%20interface",
        "https://github.com/sagemath/sage/labels/p%3A%201%20%E2%80%93%20blocker",
        "https://github.com/sagemath/sage/labels/bug"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-3.1",
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "notebook -- SyntaxWarning in twist.py",
    "type": "issue",
    "updated_at": "2008-08-13T06:39:15Z",
    "url": "https://github.com/sagemath/sage/issues/3816",
    "user": "https://github.com/williamstein"
}
```
this was in there forever, but for some reason it causes a warning...

From Cremona:

```

I have a successful build of 3.1.alpha1.  When I make a clone, the
*first* time I run sage (by typing ./sage in SAGE_ROOT right after the
sage -clone) I get this message after the banner and before the first
prompt:

/home/john/sage-3.1.alpha1/local/lib/python2.5/site-packages/sage/server/notebook/twist.py:1762:
SyntaxWarning: name 'notebook' is used prior to global declaration
 global notebook

But if I then quit and restart, the message does not recur.

What gives?

John

```

Component: **notebook**

_Issue created by migration from https://trac.sagemath.org/ticket/3816_





---

archive/issue_events_042287.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2008-08-12T13:16:44Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "milestone_number": null,
    "milestone_title": "sage-3.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/3816#event-42287"
}
```



---

archive/issue_events_042288.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2008-08-12T13:16:44Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20user%20interface",
    "label_color": "000080",
    "label_name": "c: user interface",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/3816#event-42288"
}
```



---

archive/issue_events_042289.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2008-08-12T13:16:44Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "label": "https://github.com/sagemath/sage/labels/p%3A%201%20%E2%80%93%20blocker",
    "label_color": "ff0000",
    "label_name": "p: 1 \u2013 blocker",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/3816#event-42289"
}
```



---

archive/issue_events_042290.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2008-08-12T13:16:44Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/3816#event-42290"
}
```



---

archive/issue_events_042291.json:
```json
{
    "actor": "https://github.com/boothby",
    "created_at": "2008-08-12T13:16:44Z",
    "event": "assigned",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "subject": "https://github.com/williamstein",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/3816#event-42291"
}
```



---

archive/issue_events_042292.json:
```json
{
    "actor": "https://github.com/williamstein",
    "created_at": "2008-08-12T13:16:44Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/3816#event-42292"
}
```



---

archive/issue_comments_021087.json:
```json
{
    "body": "Attachment: **[sage-3816.patch.gz](https://github.com/sagemath/sage/files/ticket3816/sage-3816.patch.gz)**",
    "created_at": "2008-08-12T13:17:10Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/3816#issuecomment-21087",
    "user": "https://github.com/williamstein"
}
```

Attachment: **[sage-3816.patch.gz](https://github.com/sagemath/sage/files/ticket3816/sage-3816.patch.gz)**



---

archive/issue_comments_021088.json:
```json
{
    "body": "<div id=\"comment:1\" align=\"right\">comment:1</div>\n\nPositive review. Patch looks good to me.\n\nCheers,\n\nMichael",
    "created_at": "2008-08-13T06:38:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/3816#issuecomment-21088",
    "user": "https://github.com/sagetrac-mabshoff"
}
```

<div id="comment:1" align="right">comment:1</div>

Positive review. Patch looks good to me.

Cheers,

Michael



---

archive/issue_events_042293.json:
```json
{
    "actor": "https://github.com/sagetrac-mabshoff",
    "created_at": "2008-08-13T06:38:26Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/3816#event-42293"
}
```



---

archive/issue_events_042294.json:
```json
{
    "actor": "https://github.com/sagetrac-mabshoff",
    "created_at": "2008-08-13T06:39:15Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/3816#event-42294"
}
```



---

archive/issue_events_042295.json:
```json
{
    "actor": "https://github.com/sagetrac-mabshoff",
    "created_at": "2008-08-13T06:39:15Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/3816#event-42295"
}
```



---

archive/issue_comments_021089.json:
```json
{
    "body": "<div id=\"comment:2\" align=\"right\">comment:2</div>\n\nMerged in Sage 3.1.alpha2",
    "created_at": "2008-08-13T06:39:15Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/3816",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/3816#issuecomment-21089",
    "user": "https://github.com/sagetrac-mabshoff"
}
```

<div id="comment:2" align="right">comment:2</div>

Merged in Sage 3.1.alpha2
